"""Add EmailCampaign and update EmailTemplate

Revision ID: 561a9ad02026
Revises: 99f5992375ae
Create Date: 2026-04-11 00:20:32.608889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561a9ad02026'
down_revision: Union[str, None] = '99f5992375ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('target_application_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('audience_count', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_recruiter', 'email_campaigns', ['recruiter_id'], unique=False)
    op.create_index('idx_campaign_status', 'email_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_email_campaigns_id'), 'email_campaigns', ['id'], unique=False)
    op.add_column('email_templates', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_templates', 'category')
    op.drop_index(op.f('ix_email_campaigns_id'), table_name='email_campaigns')
    op.drop_index('idx_campaign_status', table_name='email_campaigns')
    op.drop_index('idx_campaign_recruiter', table_name='email_campaigns')
    op.drop_table('email_campaigns')
    # ### end Alembic commands ###
