"""Initial migration

Revision ID: c66d84bde0a1
Revises: 
Create Date: 2026-04-05 22:28:46.572605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66d84bde0a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CANDIDATE', 'RECRUITER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_website', sa.String(length=200), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('smtp_server', sa.String(length=200), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_email', sa.String(length=200), nullable=True),
    sa.Column('smtp_password', sa.String(length=500), nullable=True),
    sa.Column('smtp_from_name', sa.String(length=200), nullable=True),
    sa.Column('smtp_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('salary_range', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Enum('IT', 'FINANCE', 'MARKETING', 'SALES', 'HEALTHCARE', 'EDUCATION', 'ENGINEERING', 'DESIGN', 'OPERATIONS', 'HR', 'OTHER', name='jobcategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_category'), 'jobs', ['category'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('resume_path', sa.String(length=255), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('APPLIED', 'SHORTLISTED', 'INTERVIEW', 'REJECTED', 'HIRED', name='applicationstatus'), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('skill_match_score', sa.Float(), nullable=True),
    sa.Column('experience_match_score', sa.Float(), nullable=True),
    sa.Column('semantic_similarity_score', sa.Float(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('job_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('processed_text', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('preferred_skills', sa.JSON(), nullable=True),
    sa.Column('description_embedding', sa.JSON(), nullable=True),
    sa.Column('requirements_embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('processing_model', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_job_embeddings_id'), 'job_embeddings', ['id'], unique=False)
    op.create_table('job_tags',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'tag_id')
    )
    op.create_table('candidate_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('overall_rank', sa.Integer(), nullable=True),
    sa.Column('percentile_rank', sa.Float(), nullable=True),
    sa.Column('skill_match_count', sa.Integer(), nullable=True),
    sa.Column('required_skills_matched', sa.Integer(), nullable=True),
    sa.Column('total_required_skills', sa.Integer(), nullable=True),
    sa.Column('experience_gap', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('education_score', sa.Float(), nullable=True),
    sa.Column('overall_fit_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'application_id', name='unique_job_application_ranking')
    )
    op.create_index('idx_candidate_rankings_job_id', 'candidate_rankings', ['job_id'], unique=False)
    op.create_index('idx_candidate_rankings_job_rank', 'candidate_rankings', ['job_id', 'overall_rank'], unique=False)
    op.create_index('idx_candidate_rankings_job_score', 'candidate_rankings', ['job_id', 'overall_fit_score'], unique=False)
    op.create_index(op.f('ix_candidate_rankings_id'), 'candidate_rankings', ['id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('interviewer_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('proposed_time', sa.DateTime(), nullable=True),
    sa.Column('reschedule_reason', sa.String(length=1000), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('interview_type', sa.Enum('PHONE', 'VIDEO', 'IN_PERSON', 'TECHNICAL', name='interviewtype'), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', 'RESCHEDULE_REQUESTED', name='interviewstatus'), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('candidate_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP', name='employmenttype'), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('signing_bonus', sa.Float(), nullable=True),
    sa.Column('stock_options', sa.Float(), nullable=True),
    sa.Column('benefits_summary', sa.Text(), nullable=True),
    sa.Column('custom_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'WITHDRAWN', name='offerstatus'), nullable=True),
    sa.Column('offer_letter_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('response_action', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index('idx_offer_candidate_id', 'offers', ['candidate_id'], unique=False)
    op.create_index('idx_offer_expires_at', 'offers', ['expires_at'], unique=False)
    op.create_index('idx_offer_job_id', 'offers', ['job_id'], unique=False)
    op.create_index('idx_offer_status', 'offers', ['status'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_table('resume_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('personal_info', sa.JSON(), nullable=True),
    sa.Column('work_history', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('total_experience_years', sa.Float(), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_model', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('text_embedding', sa.JSON(), nullable=True),
    sa.Column('skills_embedding', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resume_data_application', 'resume_data', ['application_id'], unique=False)
    op.create_index('idx_resume_data_candidate', 'resume_data', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resume_data_id'), 'resume_data', ['id'], unique=False)
    op.create_table('employee_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP', name='employmenttype'), nullable=True),
    sa.Column('contract_path', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_email', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True),
    sa.Column('tax_form_w4_path', sa.String(length=255), nullable=True),
    sa.Column('i9_form_path', sa.String(length=255), nullable=True),
    sa.Column('nda_signed', sa.Boolean(), nullable=True),
    sa.Column('handbook_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('onboarding_status', sa.String(length=20), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_employee_record_employee_id', 'employee_records', ['employee_id'], unique=False)
    op.create_index('idx_employee_record_user_id', 'employee_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_employee_records_id'), 'employee_records', ['id'], unique=False)
    op.create_table('offer_negotiations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('initiated_by', sa.String(length=50), nullable=False),
    sa.Column('proposed_salary', sa.Float(), nullable=True),
    sa.Column('proposed_benefits', sa.Text(), nullable=True),
    sa.Column('proposed_signing_bonus', sa.Float(), nullable=True),
    sa.Column('proposed_stock_options', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_negotiation_offer_id', 'offer_negotiations', ['offer_id'], unique=False)
    op.create_index('idx_negotiation_status', 'offer_negotiations', ['status'], unique=False)
    op.create_index(op.f('ix_offer_negotiations_id'), 'offer_negotiations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_negotiations_id'), table_name='offer_negotiations')
    op.drop_index('idx_negotiation_status', table_name='offer_negotiations')
    op.drop_index('idx_negotiation_offer_id', table_name='offer_negotiations')
    op.drop_table('offer_negotiations')
    op.drop_index(op.f('ix_employee_records_id'), table_name='employee_records')
    op.drop_index('idx_employee_record_user_id', table_name='employee_records')
    op.drop_index('idx_employee_record_employee_id', table_name='employee_records')
    op.drop_table('employee_records')
    op.drop_index(op.f('ix_resume_data_id'), table_name='resume_data')
    op.drop_index('idx_resume_data_candidate', table_name='resume_data')
    op.drop_index('idx_resume_data_application', table_name='resume_data')
    op.drop_table('resume_data')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index('idx_offer_status', table_name='offers')
    op.drop_index('idx_offer_job_id', table_name='offers')
    op.drop_index('idx_offer_expires_at', table_name='offers')
    op.drop_index('idx_offer_candidate_id', table_name='offers')
    op.drop_table('offers')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_candidate_rankings_id'), table_name='candidate_rankings')
    op.drop_index('idx_candidate_rankings_job_score', table_name='candidate_rankings')
    op.drop_index('idx_candidate_rankings_job_rank', table_name='candidate_rankings')
    op.drop_index('idx_candidate_rankings_job_id', table_name='candidate_rankings')
    op.drop_table('candidate_rankings')
    op.drop_table('job_tags')
    op.drop_index(op.f('ix_job_embeddings_id'), table_name='job_embeddings')
    op.drop_table('job_embeddings')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_category'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
